trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- task: AzureCLI@2
  inputs:
    azureSubscription: 'Pay As You Go(c61095aa-0afd-4d68-922d-90796651f1a7)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      docker build -t gopalacr13.azurecr.io/web-game:tag 2048-game
      az acr login -n gopalacr13
      docker push gopalacr13.azurecr.io/web-game:tag 2048-game

- script: cat - task: Kubernetes@1
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscriptionEndpoint: 'Pay As You Go(c61095aa-0afd-4d68-922d-90796651f1a7)'
    azureResourceGroup: 'ubuntu_group'
    kubernetesCluster: 'gopalaks'
    namespace: 'default'
    command: 'apply'
    useConfigurationFile: true
    configuration: '01_kubernetes_aks'
    secretType: 'dockerRegistry'
    containerRegistryType: 'Azure Container Registry'
    azureSubscriptionEndpointForSecrets: 'Pay As You Go(c61095aa-0afd-4d68-922d-90796651f1a7)'
    azureContainerRegistry: 'gopalacr13.azurecr.io'
    forceUpdate: false/app-depoy.yaml

